# https://developer.android.com/build/migrate-to-catalogs

[versions]

detekt = "1.23.8"
dokka = "2.1.0"
exposed = "1.0.0-rc-4"
h2 = "2.3.232"
kotest = "6.0.0.M1"
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
ktor = "3.3.2"
vanniktech = "0.35.0"


[plugins]

# Detekt.
# https://github.com/detekt/detekt/releases
# https://github.com/detekt/detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# Dokka.
# https://github.com/Kotlin/dokka/releases
# https://github.com/Kotlin/dokka
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

# Kotlin JVM.
# https://github.com/JetBrains/kotlin/releases
# https://github.com/JetBrains/kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# Kotlin Serialization.
# https://github.com/Kotlin/kotlinx.serialization/releases
# https://github.com/Kotlin/kotlinx.serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Gradle Maven Publish Plugin.
# https://github.com/vanniktech/gradle-maven-publish-plugin/releases
# https://github.com/vanniktech/gradle-maven-publish-plugin
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }


[libraries]

# Detekt.
# https://github.com/detekt/detekt/releases
# https://github.com/detekt/detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Exposed ORM.
# https://github.com/JetBrains/Exposed/releases
# https://github.com/JetBrains/Exposed
# https://github.com/JetBrains/Exposed/blob/main/docs/ChangeLog.md
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

# Serialization (part of the pLugin).
# https://github.com/Kotlin/kotlinx.serialization/releases
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Ktor.
# https://github.com/ktorio/ktor/releases
# https://api.ktor.io
# https://github.com/ktorio/ktor
# https://ktor.io/docs/releases.html#release-details
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

# Testing libraries.
# https://github.com/kotest/kotest/releases
# https://github.com/kotest/kotest
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

# H2 Database.
# https://github.com/h2database/h2database/releases
h2 = { module = "com.h2database:h2", version.ref = "h2" }

# Ktor Test Host.
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# --- Gradle Build Plugins ---
gradle-kotlin-jvm = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktech" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
gradle-dokka = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
gradle-kotlin-serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
